@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMzMDk3NTd9.oEqSpzrwRzDukPiOHltj8K2wde9aQ17P-FQ3FKYN1CA
@domain = http://localhost:3000

GET {{domain}}/products

###

GET {{domain}}/products/7

###
POST {{domain}}/products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "rubber duck",
  "price": 5,
  "description": "your portable therapist and counsleor for when your code just doesn't work like they used to.",
  "inventory": 30,
  "supplier_id": 2
}

###
PATCH {{domain}}/products/1
Content-Type: application/json

{
"inventory": 25

}

###
DELETE {{domain}}/products/5

### Users create (signup)
POST {{domain}}/users
Content-Type: application/json

{
  "name": "Lebowski",
  "email": "His-Dudeness@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{domain}}/sessions
Content-Type: application/json

{
  "email": "Admin@gmail.com",
  "password": "password"
}

### products create
POST {{domain}}/orders
Content-Type: application/json

{
  "product_id": 1,
  "user_id": 1,
  "quantity": 3,
  "subtotal": 1.00,
  "tax": 2.00,
  "total": 3.00
}

###
GET {{domain}}/orders/1

###
GET {{domain}}/orders

###
POST {{domain}}/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 4,
  "quantity": 3
}

###
GET {{domain}}/orders
Authorization: Bearer {{jwt}}

###
GET {{domain}}/orders
Authorization: Bearer {{jwt}}