
GET http://localhost:3000/products

###

GET http://localhost:3000/products/7

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Book",
  "price": 5,
  "description": "An intro-level book on making books."
}

###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
"inventory": 25

}

###
DELETE http://localhost:3000/products/5

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Lebowski",
  "email": "His-Dudeness@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "His-Dudeness@gmail.com",
  "password": "password"
}

### products create
POST http://localhost:3000/orders
Content-Type: application/json

{
  "product_id": 1,
  "user_id": 1,
  "quantity": 3,
  "subtotal": 1.00,
  "tax": 2.00,
  "total": 3.00
}

###
GET http://localhost:3000/orders/1

###
GET http://localhost:3000/orders

###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMyMjMwOTV9.1rJYgrQcpx5vJ_Bw53JzSOqt76hJQeZV40hcUB1ag3k

{
  "product_id": 4,
  "quantity": 3
}

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMyMjMwOTV9.1rJYgrQcpx5vJ_Bw53JzSOqt76hJQeZV40hcUB1ag3k

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMyMjMwOTV9.1rJYgrQcpx5vJ_Bw53JzSOqt76hJQeZV40hcUB1ag3k