
GET http://localhost:3000/products

###

GET http://localhost:3000/products/7

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Book",
  "price": 5,
  "description": "An intro-level book on making books."
}

###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
"inventory": 25

}

###
DELETE http://localhost:3000/products/5

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Lebowski",
  "email": "His-Dudeness@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "His-Dudeness@gmail.com",
  "password": "password"
}

### products create
GET  http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDMxNDE3NjF9.fOOTKfTjjhwR8Af_-jUQzuV2daiMQH5vtbUewbM3rkU
Content-Type: application/json
